name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          command_timeout: 20m
          script: |
            cd /home/ec2-user/la-penca
            git pull
            docker build -t la-penca .
            docker stop lapenca-app || true
            docker rm lapenca-app || true
            docker run -d --name lapenca-app --network lapenca-network -p 8080:8080 --restart unless-stopped -e JDBC_DATABASE_URL=jdbc:postgresql://lapenca-db:5432/lapenca -e DB_USERNAME=postgres -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e PORT=8080 la-penca